spring:
  cloud:
    function:
      definition: consumerTest
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - 192.168.10.103:9092
          configuration:
            partition.assignment.strategy: org.apache.kafka.clients.consumer.RoundRobinAssignor
          auto-add-partitions: true
        bindings:
          consumerTest-in-0:
            consumer:
              # Dead Letter Queue Configuration
              # https://cloud.spring.io/spring-cloud-static/spring-cloud-stream-binder-kafka/3.0.6.RELEASE/reference/html/spring-cloud-stream-binder-kafka.html#kafka-consumer-properties
              enableDlq: true
              dlqName: topic1-dlq
              dlqPartitions: 1

      bindings:
        consumerTest-out-0:
          destination: topic1
          producer:
            partition-count: 10
        consumerTest-in-0:
          destination: topic1
          group: group1
          consumer:
            partitioned: true
            concurrency: 7

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://192.168.10.103:3306/test?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
